scripts/check_compliance.py

As suggested by Ulf Magnusson in the previous PR #18, move all the
logging initialization in the init_logs() function.
Remove the switch/case parsing the log level name because Python does
that for free.

check_compliance.py: simplify init_logs()

---

scripts/check_compliance.py

There's not always an _elem.text. To test:
ZEPHYR_BASE=/whatever ./scripts/check_compliance.py -m Kconfig
- Before:
AttributeError: 'NoneType' object has no attribute 'strip'
- After:
Running Kconfig tests...
1 Errors found
ERROR   : Test Kconfig failed: Can't find Kconfig

check_compliance.py: fallback on result.message when no ._elem.text

---

scripts/check_compliance.py

The only indication that a test has been skipped (for instance because
checkpatch or scancode couldn't be found) requires opening the
compliance.xml file.
Log a warning() for every skipped test including the reason why it was
skipped.  Also remind users that the complete, reference results for CI
are in the XML file so they realize the standard output is informative
and sometimes approximative.
Sample output:
WARNING : Skipped checkpatch, checkpatch script not found
WARNING : Skipped Kconfig, Not a Zephyr tree
WARNING : Skipped License, scancode-toolkit not installed

check_compliance.py: warn about skipped tests and no .result

---

requirements.txt

` check_compliance.py` uses colorama which was not in requirements.txt

bugfix: missing requirement in requirements.txt for check_compliance.py

---

scripts/check_compliance.py

Replace with Error(msg, "error")
Typo introduced in previous commit / PR #26. Fixes the following
console output:
WARNING : Skipped Gitlint failed: ...
I don't know the impact on Github however this just restores the
previous behavior.

check_compliance.py: fix Error(msg, "skipped")

---

scripts/check_compliance.py

Fail the CODEOWNERS check if there are missing trailing slashes or
missing paths, instead of just printing a warning to stderr. Otherwise,
bad entries will probably keep getting added to CODEOWNERS.
Clarify the error message when / is missing too.

checks: codeowners: Fail on missing trailing / and missing paths

---

scripts/check_compliance.py

Counterpart to Zephyr PR:
https://github.com/zephyrproject-rtos/zephyr/pull/14976
Part of the solution for:
https://github.com/zephyrproject-rtos/zephyr/issues/14974
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

check_compliance: Use CMAKE_BINARY_DIR for Kconfig.modules

---

scripts/check_compliance.py

Use 'git grep' to look for the pattern CONFIG_[A-Z0-9_]+ at word
boundaries in all files. For each match, check that the corresponding
Kconfig symbol is defined.
This check is broad enough that it will always need some whitelisting,
e.g. due to token pasting (CONFIG_FOO_#x) and non-existent symbols used
as examples. The message printed on failures points out where the
whitelist is.
There's a few stragglers in the whitelist for small issues that are
about to be fixed (the issue IDs are included).
Skip the samples/ and tests/ directories for now. They contain Kconfig
files that aren't part of the main Kconfig tree, which triggers false
positives. Maybe something fancier could be done later to include those.

checks: kconfig: Check for references to undefined Kconfig symbols

---

scripts/check_compliance.py
scripts/gitlint/zephyr_commit_rules.py
scripts/merge_junit.py

Fixes pylint warnings like this one:
scripts/check_compliance.py:326:0: W1401: Anomalous backslash in
string: '\s'. String constant might be missing an r prefix.
(anomalous-backslash-in-string)
The reason for this warning is that backslash escapes are interpreted in
non-raw (non-r-prefixed) strings. For example, '\a' and r'\a' are not
the same string (first one has a single ASCII bell character, second one
has two characters).
It just happens that there's no \s (or \\., or \\/) escape for example,
and '\s' turns into two characters (as needed for a regex). It's risky
to rely on stuff like that regexes though. Best to make them raw strings
unless they're super trivial.
Also note that '\s' and '\\\\s' turn into the same string.
Another tip: A literal ' can be put into a string with …

scripts: Fix risky uses of non-raw regex strings in Python scripts

---

scripts/check_compliance.py

PR #42 / Commit 4a2a1e17a488 "Use zephyr_module.py to generate
Kconfig.modules" totally failed to handle exceptions by trying to re-use
bits of existing code which was meant for something completely
different: - exception name mismatch ("ex" vs "e"); - irrelevant
sh.CommandNotFound exception left over; - use of the low-level
popen()/pcommunicate() which rarely ever raise exceptions; ...
To reproduce the issue, temporarily rename 'scripts/zephyr_module.py' to
something else and observe the Kconfig check silently passing despite
the lack of the main script and thanks to a /tmp/Kconfig.modules file
left behind by some previous run.
Clean-up the mess and simplify the code thanks to the higher-level and
recommended subprocess.run().
Maybe any /tmp/Kconfig.modules leftover should also be …

check_compliance.py: fix broken exception handling in Kconfig

---

scripts/check_compliance.py

Also explain why we can't just "warn_to_stderr=False" our way out of it.

check_compliance.py: add comment explaining why Kconfig prints twice

---

requirements.txt

CVE-2019-11324 More information
The urllib3 library before 1.24.2 for Python mishandles certain cases
where the desired set of CA certificates is different from the OS store
of CA certificates, which results in SSL connections succeeding in
situations where a verification failure is the correct outcome. This is
related to use of the ssl_context, ca_certs, or ca_certs_dir argument.

requirements: require urllib3>=1.24.2

---

scripts/check_compliance.py

The initial purpose was to replace glob.glob(**, recursive=True) with
pathlib.Path.glob(**) because the former follows symbolic links to
directories in recursive mode (including "infinite" loops), whereas the
latter (and more modern) doesn't. While trying to stick to this change,
testing found a significant number of other issues and addressing all of
them unfortunately turned into this significant rewrite. The entire
Codeowners check is too small to isolate every change in separate
commit, sorry for the resulting "bulk" review work load (~100 lines)
Here's a simplified and extreme reproduction:
- run a fairly extensive sanitycheck run. This creates 100,000s of files
in sanity-out (thank you cmake)
- observe how check_compliance.py -m Codeowners now takes minutes
- create the following …

Codeowners: replace glob with pathlib. Many other fixes.

---

scripts/check_compliance.py

When run outside ZEPHYR_BASE, the tests in check_compliance.py behave in
various ways: some check the current repo while others stick to
ZEPHYR_BASE. Some run in a subdirectory while others stick to GIT_TOP,
Some don't mind being run from a subdirectory while others fail.
Some of these inconsistencies make sense while others are limitations
that should probably be fixed. However the first step is awareness and
clarifying mysteries so this commit purely prints which (sub)directory
is being checked for every test while making absolutely zero functional
change.
Sample output:
```
cd zephyr-ci-tools/scripts/
Running checkpatch       in /home/joe/zephyr-ci-tools ...
Running Kconfig          in /home/joe/zephyr ...
Running Codeowners       in /home/joe/zephyr-ci-tools ...
Running Documentation …
```

check_compliance.py: show which (sub)directory is being checked

---

scripts/check_compliance.py
scripts/gitlint/zephyr_commit_rules.py
scripts/merge_junit.py

The docstring needs to come first in the file. Fixes these pylint
warnings:
```
scripts/gitlint/zephyr_commit_rules.py:21:-1: W0105: String statement has no effect (pointless-string-statement)
scripts/merge_junit.py:15:-1: W0105: String statement has no effect (pointless-string-statement)
```
Also fix a misindented line that got flagged.

scripts: Fix broken module docstrings and bad indentation

---

scripts/check_compliance.py

gitlint is very "flexible" - and confusing: it can run from any
sub-directory but looks for .gitlint configuration only in the current
directory. For instance running:
check_compliance.py -c 4fc250489d~..
... in this repo reports a slightly different set of issues depending on
what the current sub-directory is.
Zephyr is not interested in per-directory rules right now; always run
gitlint in GIT_TOP where the single .gitlint is.

check_compliance.py: run gitlint in GIT_TOP

---

scripts/check_compliance.py

The sh library (https://amoffat.github.io/sh/) is only used to run Git,
and each call to sh.git() currently passes _tty_out=False to prevent Git
from starting a pager (through sh_special_args).
Add comments to explain what 'sh' is, why _tty_out=False is there, and
add a helper function for running Git. That way the mysterious
sh_special_args dictionary can be removed as well.
Importing a library just for running Git might be overkill, but this
should immediately demystify what's going on at least.
Another issue with the 'sh' library is that it doesn't work on Windows.

check_compliance.py: Add Git helper and get rid of sh_special_args

---

scripts/check_compliance.py

--only-matching was added to 'git grep' during the second half of 2018,
so relying on it is shaky. Rewrite check_no_undef_outside_kconfig() to
manually extract the symbol reference(s) from each matching line
instead.
Also fix an issue with a literal '{' in a string passed to .format()
that raises an error. Needs to be doubled.
The format of the Kconfig whitelist was changed to omit the CONFIG_
prefix from each entry.

check_compliance.py: Avoid using newly-added 'git grep --only-matching'

---

scripts/check_compliance.py

This fixes two issues:
- An overly agressive optimization that returned before checking the
CODEOWNERS files on renames and deletions. This could leave stale
entries in CODEOWNERS which are noticed (much) later by the next
commit adding new files. See example in PR [#17075](https://github.com/zephyrproject-rtos/zephyr/pull/17075) paying the price for
PR [#17054](https://github.com/zephyrproject-rtos/zephyr/pull/17054) and others. This is fixed by moving the recursive scan earlier and
making the optimization less agressive.
- A simpler, one-missing-character bug that failed to include moved
files in the set of new files. Since CODEOWNERS is path-based they
must be treated as such.

codeowners: add missing checks on renames and deletions

---

scripts/check_compliance.py

Do not allow comma in path, this is not allowed by Github parser.

codeowner: do not allow commas

---

scripts/what_changed.py

Add a new entry for the newly created Bluetooth Mesh label.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

what_changed: Add entry for Bluetooth Mesh

---

CODEOWNERS
scripts/check_compliance.py
scripts/pylintrc

Run pylint on new/modified *.py files and fail if there are any
warnings.
Only enable a limited set of checks, focusing on logic issues and
relatively uncontroversial style stuff. We can tweak what checks are
enabled as we go.

check_compliance.py: Run pylint on Python scripts

---

scripts/check_compliance.py

Makes things a bit clearer when reading main(). Suggested by Marc.

check_compliance.py: Move needs-GitHub check outside init_github()

---

scripts/check_compliance.py

The tip re. the bot editing comments instead of posting new ones appears
in all comments, so it can be used to detect old comments, instead of
looking for several different messages.
Gets rid of the PASS_MSG, FAIL_MSG, and ERR_MSG variables.

check_compliance.py: Refactor detection of old bot messages

---

requirements.txt
scripts/check_compliance.py

Use the python-magic library to detect added/changed Python files even
if they don't end in .py. This will detect e.g.
scripts/footprint/size_report in the Zephyr repo.
scripts/sanitycheck is currently being overhauled, so skip it manually
for now. It will be checked later.

check_compliance.py: pylint: Detect Python files not ending in .py

---

scripts/check_compliance.py

Everything that should've been formatted wasn't, and vice versa.
Misunderstood the old code and didn't notice the 'not'.

check_compliance.py: Fix formatting mess-up for error messages

---

requirements.txt
scripts/check_compliance.py
scripts/what_changed.py

Two fixes, which together get rid of all warnings for `what_changed.py` and get rid of the `sh` library.
Getting rid of the `sh` library was prompted by fixing the warnings, but it seems to have other nice side effects too, like Windows compatibility (for the Git part at least).
```
what_changed.py: Remove unused variables and imports
Fixes pylint warnings and makes the script easier to read.
Also fix two regex-related warnings:
what_changed.py:273:0: W1401: Anomalous backslash in string: '\.'.
String constant might be missing an r prefix.
(anomalous-backslash-in-string)
There's still two warnings related to the 'sh' library. Those will be
fixed separately by removing it.
```
```
check_compliance.py/what_changed.py: Remove 'sh' library dependency
Having this third-party library just for …
```

check_compliance.py/what_changed.py: Remove 'sh' library dependency and fix pylint warnings

---

scripts/check_compliance.py

The 'sh' library seems to have some magic for iterating over lines,
which the License check relied on (maybe accidentally). The check broke
when the 'sh' library was removed in commit 3f6c5f9
("check_compliance.py/what_changed.py: Remove 'sh' library dependency
and fix pylint warnings"):
Traceback (most recent call last):
File ".../check_compliance.py", line 1210, in main
n_fails = _main(args)
File ".../check_compliance.py", line 1156, in _main
test.run()
File ".../check_compliance.py", line 780, in run
copyfile(file, copy)
File ".../shutil.py", line 114, in copyfile
with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'b'
(The 'b' there is the first character of a filename.)
Fix it by running .splitlines() on the reusult of git().
Make a similar change to …

check_compliance.py: Fix Licence and Codeowners checks

---

scripts/check_compliance.py

libmagic doesn't consider the filename when guessing the file type, and
mis-detects kconfiglib.py as HTML for example.
Treat all files with a .py extension as Python, and only use libmagic
for other files.

check_compliance.py: Treat all .py files as Python in pylint check

---

scripts/check_compliance.py

First commit adds support for informational messages from tests. Second commit uses it to report warnings from the `CheckPatch` test, even when there are no errors that would fail the test.
```
check_compliance.py: Add support for informational messages
Add a new ComplianceTest.add_info() function for showing informational
messages in tests without failing the test. Informational messages are
always shown on GitHub, regardless of whether the test succeeds or not.
CI runs check_compliance.py several times and keeps track of test
results by saving them to JUnit XML files that later get loaded, which
complicates things. To preserve informational messages, save them in a
new 'info_msg' attribute on <testcase> (added via the custom MyCase
class).
Piggyback removal of a declared-but-unused …
```

check_compliance.py: Always show warnings from checkpatch.pl

---

requirements.txt

This commit adds `cbor==1.0.0` to the `requirements.txt` file. This
is required for TF-M tests to pass in CI with Zephyr RTOS for
https://github.com/zephyrproject-rtos/zephyr/pull/19985
Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>

python: add cbor 1.0.0 support

---

scripts/check_compliance.py

https://github.com/zephyrproject-rtos/zephyr/pull/20212 fixes the last
pylint warnings in the script. Once that one is in, this can be merged.

check_compliance.py: Run pylint on scripts/sanitycheck

---

scripts/check_compliance.py

Since this check is often a manual-inspection type thing, turn it into
an informational message instead of a failure. That might avoid people
needlessly changing stuff just to please the check and get a green
checkmark, or people holding off on their review because they think
there's problems with the code.
Also encourage a compact style in the message.

check_compliance.py: Make license check informational

---

scripts/gitlint/zephyr_commit_rules.py

'if len(urls) > 0:' can be simplified to 'if urls:'. Fixes this
pylint warning:
************* Module zephyr_commit_rules
scripts/ci/gitlint/zephyr_commit_rules.py:119:11: C1801: Do not use
`len(SEQUENCE)` to determine if a sequence is empty
(len-as-condition)

zephyr_commit_rules.py: Fix pylint warning re. 'len(urls) > 0'

---

scripts/check_compliance.py

These are mentioned in the script itself. They need to be whitelisted
before ci-tools can be merged back into the main Zephyr repository,
because that makes the Kconfig checks run on check_compliance.py itself.
Use CONFIG_FOO as an example instead of CONFIG_BAZ to fix one of the
references. CONFIG_FOO is already whitelisted.

check_compliance.py: Whitelist example symbols from the script itself

---

scripts/check_compliance.py

This reverts commit 747795b933555036af09ed7de7e76900aaec7b3b.
We want the license check to error out.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

Revert "check_compliance.py: Make license check informational"

---

scripts/check_compliance.py

Will work once https://github.com/zephyrproject-rtos/zephyr/pull/20597
is in. CI uses Python 3.5, so they have been skipped until now.

check_compliance.py: Run the dtlib/edtlib test suites on Python 3.5

---

scripts/check_compliance.py

Needed for https://github.com/zephyrproject-rtos/zephyr/pull/20722.
Signed-off-by: Ulf Magnusson <Ulf.Magnusson@nordicsemi.no>

check_compliance.py: Add STACK_SIZE to Kconfig symbol whitelist

---

scripts/check_compliance.py

Needs to be updated after commit 187a2fc640 ("check_compliance.py:
Remove prepare(), add 'path' class variable, misc.") was merged.

check_compliance.py: Fix Nits test after prepare() was removed

---

scripts/check_compliance.py

Needed for https://github.com/zephyrproject-rtos/zephyr/pull/20757.

check_compliance.py: s/GENERATED_DTS_BOARD_CONF/DEVICETREE_CONF/

---

scripts/check_compliance.py

The PyLint and KconfigCheck tests are broken when not run from the
top-level repository directory. Fix it by making the path to pylintrc
absolute and explicitly running the 'git grep' for Kconfig definitions
in samples/ and tests/ from the top-level Zephyr directory.
The root cause was a mismatch between paths and process working
directories.

check_compliance.py: Fix running Kconfig/pylint checks outside top dir

---

requirements.txt

The KconfigCheck test in check_compliance.py uses
scripts/kconfig/kconfiglib.py from Zephyr, and nothing else needs
Kconfiglib to be installed from PyPI either.
Installing the old 10.30.0 version of Kconfiglib makes pylint generate a
warning-turned-error for genrest.py, because it uses a the
suppress_traceback parameter to `Kconfig.__init__()`, which was added
later.

requirements.txt: Do not install (an old version of) Kconfiglib

---

scripts/check_compliance.py

Older trees don't have the GENERATED_DTS_BOARD ->
DEVICETREE_CONF renaming yet. Set GENERATED_DTS_BOARD too in the
KconfigCheck test, to make it compatible.

check_compliance.py: Make compatible with pre-DEVICETREE_CONF renaming

---

scripts/check_compliance.py

Instead of catching DeviceTreeCheck exceptions from test(e)dtlib.py all
the way up in main(), catch them in the DeviceTreeCheck test itself, and
report them with ComplianceTest.error().
That way, other tests (e.g. pylint) can still run and report to GitHub
when there are internal errors in test(e)dtlib.py.
Motivated by https://github.com/zephyrproject-rtos/zephyr/pull/22255.

check_compliance.py: Don't error out for internal test(e)dtlib errors

---

scripts/check_compliance.py

Binding YAML documents are not concatenated together, so no '...'
document separators are needed. Flag it.

check_compliance.py: Detect redundant document separators in bindings

---

scripts/check_compliance.py

Running 'git rev-parse --show-toplevel' to set GIT_TOP before _main()
prevents any errors from it from being reported to GitHub, because the
GitHub connection hasn't been initialized yet.
If there's an error, the error reporting is currently broken as well,
because git() calls err(), which is defined at the end of the file.
Initialize GIT_TOP in _main() instead of at the top level, and use a
magic "\<repo\>" string to refer to the top-level repository directory
when setting the 'ComplianceTest.path_hint' class variables instead.
Discovered while working on some unrelated error reporting improvements.
Also move the ZEPHYR_BASE initialization to a better spot, next to other
global variables.

check_compliance.py: Avoid running 'git' before _main()

---

scripts/check_compliance.py

The " ".join(shlex.quote(word) for word in cmd) pattern was starting to
get copied in a bunch of places. Add a helper for it.
Piggyback a small improvement to the Pylint test:
I discovered earlier that FileNotFoundError is also generated when the
cwd= passed to subprocess.Popen() doesn't exists, giving a really
confusing error in that case. Just remove the FileNotFoundError check.
It's a subclass of OSError, so it'll still be caught.

check_compliance.py: Add helper for formatting commands as strings

---

scripts/check_compliance.py

Can do a single regex scan on the 'git grep' output and use
--perl-regexp instead of --extended-regexp to get non-capturing groups.
Also shortens things a bit.

check_compliance.py: Clean up get_defined_syms() a bit

---

scripts/check_compliance.py

Check *.conf (e.g. prj.conf), *.dts, *.overlay, *.txt, \*defconfig\*, and
README as well.

check_compliance.py: Run the Nits test on more file types

---

scripts/check_compliance.py

If a module is excluded, do not set status to pending.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>

[1.14 branch] status: do not set pending status on excluded modules

---

scripts/check_compliance.py

We need real addresses to be able to contact authors of code.

compliance: blacklist anonymous github emails
