zephyrproject-rtos/ci-tools

- scripts/build-docs.sh
Remove old content and files when syncing docs.
> doc: delete old content when syncing

- scripts/check_compliance.py
Lets different GitHub users make use of the edit functionality.
Signed-off-by: Ulrich Myhre <ulrich.solli.myhre@nordicsemi.no>
> compliance: Fetch username from environment, when available

- scripts/check_compliance.py
The url for the guidelines has been changed.
> check_compliance: fix contribution guidelines url

- scripts/check_compliance.py
Point to correct doc guidelines link.
Fixes #11
> scripts: fix doc-guidelines link

- scripts/check_compliance.py
Report error on kconfiglib crash
> kconfig: do not crash on kconfig exceptions

- scripts/check_compliance.py
> kconfig: set GENERATED_DTS_BOARD_CONF in the environment

- scripts/check_compliance.py
As requested in https://github.com/zephyrproject-rtos/zephyr/issues/13387:
```
checks: kconfig: Add check for new items in top menu
Fail if there are more than 'max_top_items' items with prompts in the
top Kconfig menu, to catch new items being added there accidentally.
Explain how to increase 'max_top_items' in the message.
Initialize max_top_items to 50. There are 47 items with prompts in the
top-level menu now.
```
Also includes some refactoring:
```
checks: kconfig: Refactor a bit
- Get rid of 'if' ladder. Flatten the code and move error handling next
to the source of the error.
- Simplify exception handling and make it clearer that any exception
will always come from parsing the Kconfig files.
- Get rid of a redundant os.path.join()
```
That we're splitting out things into separate …
> Add check for new items being added to the top-level Kconfig menu

- scripts/check_compliance.py
Invoke init_logs() which was dormant and reads os.environ["LOG_LEVEL"]
Add new -v INFO/DEBUG/... command-line option.
Set default log level to WARN.
Log all errors at the ERROR level.
--commits defaults to the last commit.
> scripts: print test failures. Other logging and help text enhancements

- scripts/check_compliance.py
> check_compliance.py: JUnitXML.write(..., pretty=True)

- scripts/check_compliance.py
Add three helpers error(), skip(), and add_failure() to the
ComplianceTest class to signal problems running tests, skipped tests,
and test failures, respectively. These remove some boilerplate.
Derive the message passed to the Error, Skipped, and Failure
constructors from the test name.
Allow add_failure() to be called many times within the same test to
report multiple failures. This just concatenates the failure messages.
Also add some more information to some of the errors (and remove some
info from some, where things might be clear from the context).
Also turn two 'Error's in the CODEOWNERS and documentation tests into
'Failure's. 'Error' seems to be for reporting problems running the test,
and these are more like test failures.
> check_compliance.py: Add test status reporting helpers

- scripts/check_compliance.py
This can be done in a neat way with the new
`ComplianceTest.error()`/`skip()`/`add_failure()` helpers.
Have a separate function for parsing the `Kconfigs`, and a separate
function for each test. Only parse once and reuse the `kconfiglib.Kconfig`
object between tests, to save a little bit of time.
Also allow tests to raise `EndTest` themselves wherever it's handy, and
document it.
> check_compliance.py: Break Kconfig tests into several functions

- scripts/check_compliance.py
Get a list of modules and put them in a file that is parsed by Kconfig.
This is needed for verifying multi-repo configuration where some Kconfig
options are only defined in module git repo but not in the main tree.
> kconfig: generate Kconfig.modules from west list

- scripts/check_compliance.py
A couple of trivial fixes for check_compliance
> check_compliance misc fixes

- scripts/check_compliance.py
I can't find any reason to miss on all the (other) tests when only
Kconfig requires west (since very recent commit 8820c86161ec)
Instead of crashing with a stack trace this prints this:
Running checkpatch tests...
Running Kconfig tests...
Running Codeowners tests...
Running Documentation tests...
Running Gitlint tests...
Running License tests...
Running Identity/Emails tests...
WARNING : Skipped Kconfig, Command not found: west
WARNING : Skipped License, scancode-toolkit not installed
Complete results in compliance.xml
> check_compliance: don't crash when west's missing, just skip Kconfig

- scripts/check_compliance.py
> check_compliance: Fix bad indentation

- scripts/check_compliance.py
Instead of duplicating the code already present in Zephyr, reuse the
existing scripts/zephyr_module.py to generate the Kconfig.modules file
required by Kconfig.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
> check_compliance: Use zephyr_module.py to generate Kconfig.modules

- scripts/check_compliance.py
- scripts/gitlint/zephyr_commit_rules.py
- scripts/merge_junit.py
Reported by the new CI check in
https://github.com/zephyrproject-rtos/ci-tools/pull/37.
> scripts: Fix unused variables and imports

- scripts/check_compliance.py
Check license for cmake and kconfig files.
> license: check for CMakeLists.txt and Kconfig files

- scripts/check_compliance.py
> license: missing copyrights in cmake are ok

- scripts/check_compliance.py
Alter the regular expression used in git-grep to exclude simple token pasting for the form `CONFIG_STUFF##something`.  This does not catch any use for `UTIL_CAT` and friends, but it does allow removal of some elements from the whitelist.
The specific motivation is zephyrproject-rtos/zephyr#15105 where I used token pasting for counter instances.  However, this is a general solution to the simple cases like that.
> check_compliance.py: Exclude simple Kconfig token pasting

- scripts/check_compliance.py
Add more patterns to the negative lookahead in the regex, to avoid
flagging CMake variable expansion (`CONFIG_FOO_${VAR}`), CMake
`configure_file()` references (`CONFIG_FOO_@VAR@`), Python `format()` stuff
(`"CONFIG_FOO_{}_...".format(...)`), and `#endif` comments that talk about
many symbols (`#endif /* CONFIG_FOO_* */`).
This gets rid of some entries from the whitelist too.
Mention the safe #endif format in the message posted when the test
fails.
Prompted by https://github.com/zephyrproject-rtos/zephyr/pull/16222.
> check_compliance.py: Avoid more false positives in Kconfig check

- scripts/check_compliance.py
Fixed links to documentation posted in PRs as part of the status checks.
> check_compliance: fix links to documentation

- CODEOWNERS
- scripts/what_changed.py
Look at files being changed and set labels accordingly.
> set labels on PR

- scripts/check_compliance.py
zephyrproject-rtos/zephyr#17660 must go in
before this will work.
Piggyback a clarification re. ZEPHYR_BASE being None when not running on
a Zephyr tree (e.g. when running on the ci-tools repo itself).
> Run the dtlib and edtlib test suites in CI

- scripts/check_compliance.py
Disable pylint test for now, we dont have pylint in docker image.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> check_compliance: disable pylint

- scripts/check_compliance.py
This reverts commit 89e0ac76ad759ef79249339c5eadd4cecc1f287d.
Just solve this by getting pylint into CI docker image
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> Revert "check_compliance: disable pylint"

- scripts/check_compliance.py
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> job id in status

- scripts/check_compliance.py
Tabs were getting lost, causing the bot to edit the checkpatch message
to remove them the second time check_compliance.py was run (it's run
multiple times by CI, with test results saved to XML between runs). The
bot edits the comment when the text changes.
This isn't my area, but properly escaping and unescaping text for XML
attributes seems surprisingly tricky. There's
xml.sax.saxutils.quoteattr() for escaping, but there doesn't seem
anything built-in for undoing it.
Just use 'unicode-escape' instead, which should be good enough in
practice. It replaces newlines and tabs with the two-character strings
\n and \t, etc.
junitparser already deals with quotes and stuff.
> check_compliance.py: Preserve 'info_msg' better in XML

- scripts/check_compliance.py
- scripts/pylintrc
> pylint fixes: don't ignore fatal issues, run in GIT_TOP, logging

- scripts/check_compliance.py
Simplify check_compliance.py a bit to make it easier to follow, and to
make it easier to add new tests:
- Store the path printed for each test in a ComplianceTest.path_hint
class variable instead of passing it to ComplianceTest.prepare().
Print the "Running <test name> in <path> ..." message in main()
instead of in prepare().
Remove ComplianceTest.prepare() and all the calls to it, as it's no
longer needed.
- Store the commit range in a global COMMIT_RANGE variable, set in
main(), instead of passing it to ComplianceTest.prepare()
This simplifies ComplianceTest.\_\_init__() to take no args. Use
\_\_init__() to initialize ComplianceTest.case, instead of doing it in
ComplianceTest.prepare().
- Remove some unused stuff too:
* The class variables on the ComplianceTest class itself. Instead, …
> check_compliance.py: Remove prepare(), add 'path' class variable, misc.

- scripts/check_compliance.py
Similar improvements to
https://github.com/zephyrproject-rtos/zephyr/pull/21577. No custom
potentially-missing working directory is used here, but always including
the exception message still feels more robust.
Use err() instead of sys.exit() in git(), and have it include the
command name, which is helpful in logs.
> check_compliance.py: Improve error reporting for Git commands

- scripts/check_compliance.py
Add a generic kitchen-sink Nits test for various minor nits that aren't
already covered by tools like checkpatch.pl and pylint. So far checks
this:
- Header comments in Kconfig files
- Missing newlines at the end of various source files (probably a bad
editor setting)
- Leading/trailing blank lines in files
> check_compliance.py: Detect bad header comments and other nits

- scripts/check_compliance.py
Main commit:
```
check_compliance.py: Detect refs to undef. symbols in samples and tests
Extend the check for references to undefined Kconfig symbols to also
detect undefined symbols in samples and tests.
Samples and tests were skipped due to using separate Kconfig trees,
which hid the symbols defined in them. Work around it by grepping for
Kconfig symbol definitions in them instead.
Keep properly parsing the main Kconfig tree, as it's needed to see
symbol names that are stitched together with the Kconfig preprocessor.
```
Cleanup:
```
check_compliance.py: Simplify Kconfig tests with git() helper
Use the git() helper instead instead of subprocess.Popen to get rid of
some code duplication.
Also add some more comments to the Kconfig tests.
```
Needs these to be merged/fixed before it can be …
> Detect references to undef Kconfig symbols in samples and tests (and not just the main tree)

- scripts/check_compliance.py
'source's like
source "$(ZEPHYR_BASE)/Kconfig.zephyr"
can be simplified to
source "Kconfig.zephyr"
since $srctree already points to the Zephyr root.
Flag it in the `Nits` test.
This also avoids absolute paths showing up in some places.
> check_compliance.py: Kconfig: Flag redundant $ZEPHYR_BASE in 'source'

- scripts/check_compliance.py
Same check as in scripts/kconfig/lint.py in Zephyr. It's worth flagging
it in CI too.
'menuconfig' symbols without children are pointless and make the
menuconfig interface confusing. See the 'menuconfig symbols' section in
https://docs.zephyrproject.org/latest/guides/kconfig/tips.html.
> check_compliance.py: Flag pointless 'menuconfig' symbols in CI

- scripts/check_compliance.py
We a module is disabled, do not set pending in GH.
> Do not set pending on excluded modules
